[
    {
      "_id": "62cafb147c1a44758db9365a",
      "artist": "João Gilberto",
      "album": "Chega de Saudade",
      "image": "https://m.media-amazon.com/images/I/51ALG9yio+L._SS135_.jpg",
      "genre": "Bossa Nova",
      "tags": "",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/5ecK3BBBIk4xNixVydBYtZ?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "The Chega de Saudade album is supplemented by the impossibly rare EP of songs from the film Black Orpheus and recordings of some of the famous songs from Chega de Saudade by contemporaries such as Elizete Cardoso, Os Cariocas, Alaide Costa, Norma Bengell and Bola Sete. In the summer of 1958, a singer-guitarist from Bahia in the north of Brazil called João Gilberto created a musical revolution when he joined with Bossa Nova's seminal songwriting team, the gifted composer Antônio Carlos Jobim, and the poet and former diplomat, Vinicius de Moraes, to record the songs that would launch this cool, futuristic new music for a confident new era. Gilberto brought an unprecedented guitar style and a hushed, understated form of vocal expression that defined the movement and changed the course of music history. 24 tracks. El. 2010.",
      "price": 88.84,
      "access": 0,
      "stock": 99
    },
    {
      "_id": "62cafbda7c1a44758db9365b",
      "artist": "Sergio Mendes",
      "album": "Dance Moderno",
      "image": "https://m.media-amazon.com/images/I/61XfSoIWfEL._SY355_.jpg",
      "genre": "Bossa Nova",
      "tags": "",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/2YgqmtI5EW1a7uPryRZTCO?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "An essential figure in the fusion between jazz and bossa nova, pianist and composer Sérgio Mendes (age 76 at this writing) has over 55 releases under his own name. He was nominated for an Academy Award for Best Original Song in 2012 for “Real in Rio” from the animated film Rio.\nBorn on February 11, 1941 in Niterói, Rio de Janeiro, Brazil, Sérgio Mendes attended the local conservatory with hopes of becoming a classical pianist. As his interest in jazz grew, he started playing in nightclubs in the late 1950s just as bossa nova, a jazz-inflected derivative of samba, was emerging. Mendes played with Antônio Carlos Jobim (regarded as a mentor) and many U.S. jazz musicians who toured Brazil. He formed the Sexteto Bossa Rio and recorded his first album, Dance Moderno in 1961. Touring Europe and the United States, Mendes recorded albums with Cannonball Adderley and Herbie Mann and played Carnegie Hall. He moved to the U.S. in 1964 and cut two albums under the Sérgio Mendes & Brasil ’65 group name with Capitol Records and Atlantic Records.\nThe first LP on A&M was Herb Alpert Presents Sérgio Mendes and Brasil ‘66, an album that went platinum based largely on the success of the single “Mas Que Nada” (a Jorge Ben cover) and the personal support of Alpert, with whom Mendes toured.\nThough his early singles with Brasil ‘66 (most notably “Mas Que Nada”) met with some success, Mendes really burst into mainstream prominence when he performed the Oscar-nominated “The Look of Love” on the Academy Awards telecast in April 1967. Brasil ‘66’s version of the song quickly shot into the top 10, peaking at No. 4 and eclipsing Dusty Springfield’s reading from the soundtrack of the movie Casino Royale.",
      "price": 141.04,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafbec7c1a44758db9365c",
      "artist": "Buddy Holly",
      "album": "The Very Best Of Buddy Holy",
      "image": "https://m.media-amazon.com/images/I/612sT9406bL._SY355_.jpg",
      "genre": "Rock",
      "tags": "",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/14GKpFbuGksJ3gI3eyBitE?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Buddy Holly's short-lived but meteoric career has left a lasting impression on pop and rock music. He was popular music's first singer-songwriter, and the Crickets' format of two guitars, bass and drums inspired the Beatles and the beat boom that followed.",
      "price": 106.09,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafbf67c1a44758db9365d",
      "artist": "Judy Garland",
      "album": "Miss Show Business",
      "image": "https://m.media-amazon.com/images/I/613waHj+QoS._SY355_.jpg",
      "genre": "Pop",
      "tags": "",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/0uramtIEMZmRFjozebnomm?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Judy Garland's Miss Show Business was originally released in 1955 through Capitol Records and the album peaked at No. 5 on the Billboard 200. Universal Music Enterprises is now issuing the 60th Anniversary Edition, remastered on 180 gram vinyl, with notes by Lorna Luft.",
      "price": 102.71,
      "access": 0,
      "stock": 96
    },
    {
      "_id": "62cafbff7c1a44758db9365e",
      "artist": "Sam Cooke",
      "album": "The Best Of Sam Cooke",
      "image": "https://m.media-amazon.com/images/I/71ENVGoZl6L._SY355_.jpg",
      "genre": "Jazz",
      "tags": "",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/2Dpw2XUAsBvuNdNLarNzz8?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "The Best of Sam Cooke is the second greatest hits album by American singer-songwriter Sam Cooke. Produced by Hugo & Luigi, the album was released in 1962 in the United States by RCA Victor. The compilation contains most of Sam Cooke's most well-known hits from 1957 to 1962.",
      "price": 78.86,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafc0c7c1a44758db9365f",
      "artist": "Judy Garland",
      "album": "That's Entertainment",
      "image": "https://upload.wikimedia.org/wikipedia/en/c/c3/That%27s_Entertainment%21_%28Judy_Garland_album_-_cover_art%29.jpg",
      "genre": "Jazz",
      "tags": "",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/4e8L2weEFgkFQZJosoTMGi?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "That's Entertainment! is a 1960 album by the American vocalist Judy Garland arranged by Jack Marshall[1] and Conrad Salinger. Garland turned to her former MGM arranger Conrad Salinger for four full orchestra-backed songs, including the title track, “I’ve Confessed to the Breeze” from No, No, Nanette and ”Alone Together” which was selected for The Band Wagon but not ultimately used in the film.",
      "price": 107.05,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafc1a7c1a44758db93660",
      "artist": "Elvis Presley",
      "album": "Elvis' Golden Records",
      "image": "https://m.media-amazon.com/images/I/815IhKsY25L._SY355_.jpg",
      "genre": "Rock",
      "tags": "",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/0C3t1htEDTFKcg7F2rNbek?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Elvis' Golden Records is a compilation album by American rock and roll singer Elvis Presley, issued by RCA Victor in March 1958. It compiled his hit singles released in 1956 and 1957, and is widely believed to be the first greatest hits album in rock and roll history. It is the first of five RCA Victor Elvis' Golden/Gold Records compilations, the first four of which were issued during Presley's lifetime. The album peaked at number three on the Billboard Top Pop Albums chart and was certified 6× platinum on August 17, 1999, by the Recording Industry Association of America.",
      "price": 214.14,
      "access": 0,
      "stock": 98
    },
    {
      "_id": "62cafc2b7c1a44758db93661",
      "artist": "Twenty One Pilots",
      "album": "Scaled an Icy",
      "image": "https://upload.wikimedia.org/wikipedia/en/thumb/5/52/Twenty_One_Pilots_-_Scaled_and_Icy.png/220px-Twenty_One_Pilots_-_Scaled_and_Icy.png",
      "genre": "Rock",
      "tags": "Chico",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/0Q5XBpCYFgUWiG9DUWyAmJ?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Scaled and Icy is the sixth studio album by American musical duo Twenty One Pilots. The album was released on May 21, 2021, through Fueled by Ramen and Elektra. The album's title is a play on 'scaled back and isolated', a phrase frontman Tyler Joseph associated with music produced during the COVID-19 pandemic, though the phrase is also an anagram of 'Clancy is dead', a reference to the protagonist of their previous album, Trench.",
      "price": 289.32,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafc387c1a44758db93662",
      "artist": "Greta Van Fleet",
      "album": "From the Fires",
      "image": "https://upload.wikimedia.org/wikipedia/en/6/6e/Greta_Van_Fleet_From_The_Fires.jpeg",
      "genre": "Rock",
      "tags": "",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/6uSnHSIBGKUiW1uKQLYZ7w?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "From the Fires is the second EP by American rock band Greta Van Fleet. It was released on November 10, 2017 through Republic Records. From the Fires won the Grammy Award for Best Rock Album at the 61st Grammy Awards.",
      "price": 210.66,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafc717c1a44758db93663",
      "artist": "Red Hot Chilli Peppers",
      "album": "Californication",
      "image": "https://upload.wikimedia.org/wikipedia/en/thumb/d/df/RedHotChiliPeppersCalifornication.jpg/220px-RedHotChiliPeppersCalifornication.jpg",
      "genre": "Rock",
      "tags": "",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/2Y9IRtehByVkegoD7TcLfi?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Californication is the seventh studio album by the American rock band Red Hot Chili Peppers. It was released on June 8, 1999, on Warner Bros. Records and was produced by Rick Rubin. Californication marked the return of John Frusciante, who had previously appeared on Mother's Milk and Blood Sugar Sex Magik, to replace Dave Navarro as the band's guitarist. Frusciante's return was credited with changing the band's sound altogether, producing a notable shift in style from the music recorded with Navarro. The album's subject material incorporated various sexual innuendos commonly associated with the band, but also contained more varied themes than previous outings, including death, contemplations of suicide, California, drugs, globalization, and travel.",
      "price": 278.93,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafcfa7c1a44758db93664",
      "artist": "Biffy Clyro",
      "album": "Only Revolution",
      "image": "https://upload.wikimedia.org/wikipedia/en/0/03/OnlyRevolutions.jpg",
      "genre": "Rock",
      "tags": "Chico",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/6UuQatBlB5QYszvOsBawSD?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Only Revolutions is the fifth studio album by Scottish alternative rock band Biffy Clyro, released 9 November 2009 on 14th Floor Records. As with its predecessor, Puzzle, the album was produced by Garth Richardson. Upon release, Only Revolutions was a critical and commercial success. The album entered at No. 8 on the UK Album Chart and was then certified gold by the BPI shortly afterwards. It was certified platinum by the BPI in June 2010 for shipments of 300,000 copies in the UK, making it the band's largest selling album. In September 2010, the album achieved a new peak position of No. 3. It was the 26th biggest selling album of 2010 in the UK with sales of 377,900. It was nominated for the 2010 Mercury Prize, which is awarded annually for the best album in the UK or Ireland, and Rock Sound declared it third in its list of the 75 best albums of 2009.",
      "price": 227.65,
      "access": 0,
      "stock": 97
    },
    {
      "_id": "62cafd047c1a44758db93665",
      "artist": "Imagine Dragons",
      "album": "Mercury - Act 1 & 2",
      "image": "https://upload.wikimedia.org/wikipedia/en/thumb/d/d9/Imagine_Dragons_Mercury_album_cover_2022.webp/316px-Imagine_Dragons_Mercury_album_cover_2022.webp.png",
      "genre": "Rock",
      "tags": "Chico",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/6yiXkzHvC0OTmhfDQOEWtS?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Mercury – Acts 1 & 2 is a compilation album comprising Mercury – Act 1 and Mercury – Act 2, released on July 1, 2022. The double album includes the single 'Enemy' as part of Mercury – Act 1, where it appears as an additional track on the digital reissue of the album. While the standard CD edition of Mercury – Acts 1 & 2 also includes 'Enemy', the track 'I Wish' as part of the digital and 'Target Exclusive' edition of Mercury – Act 2 is not included.",
      "price": 370.24,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafd137c1a44758db93666",
      "artist": "Queen",
      "album": "A Night at the Opera (Remastered)",
      "image": "https://upload.wikimedia.org/wikipedia/en/thumb/4/4d/Queen_A_Night_At_The_Opera.png/220px-Queen_A_Night_At_The_Opera.png",
      "genre": "Rock",
      "tags": "Chico",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/75eP8LZolyNBpqIRyB5pvB?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "A Night at the Opera is the fourth studio album by the British rock band Queen, released on 21 November 1975 by EMI Records in the United Kingdom and by Elektra Records in the United States. Produced by Roy Thomas Baker and Queen, it was reportedly the most expensive album ever recorded at the time of its release.",
      "price": 287.54,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafd1f7c1a44758db93667",
      "artist": "Nirvana",
      "album": "Nevermind (Remastered)",
      "image": "https://upload.wikimedia.org/wikipedia/en/b/b7/NirvanaNevermindalbumcover.jpg",
      "genre": "Rock",
      "tags": "Chico",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/2UJcKiJxNryhL050F5Z1Fk?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Nevermind is the second studio album by the American rock band Nirvana, released on September 24, 1991, by DGC Records. It was Nirvana's first release on a major label and the first to feature drummer Dave Grohl. Produced by Butch Vig, Nevermind features a more polished, radio-friendly sound than the band's prior work. Recording took place at Sound City Studios in Van Nuys, California, and Smart Studios in Madison, Wisconsin in May and June 1991, with mastering being completed in August of that year at The Mastering Lab in Hollywood, California.",
      "price": 355.99,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafd277c1a44758db93668",
      "artist": "AC/DC",
      "album": "Back in Black",
      "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/ACDC_Back_in_Black_cover.svg/220px-ACDC_Back_in_Black_cover.svg.png",
      "genre": "Rock",
      "tags": "Chico",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/6mUdeDZCsExyJLMdAfDuwh?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Back in Black is the seventh studio album by Australian rock band AC/DC. It was released on 25 July 1980 by Albert Productions and Atlantic Records. It is the band's first album to feature lead singer Brian Johnson, following the death of previous lead singer Bon Scott.",
      "price": 271.98,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafd317c1a44758db93669",
      "artist": "Elton John",
      "album": "Goodbye Yellow Brick Road",
      "image": "https://upload.wikimedia.org/wikipedia/en/thumb/8/86/Elton_John_-_Goodbye_Yellow_Brick_Road.jpg/220px-Elton_John_-_Goodbye_Yellow_Brick_Road.jpg",
      "genre": "Rock",
      "tags": "Chico",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/5WupqgR68HfuHt3BMJtgun?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Goodbye Yellow Brick Road is the seventh studio album by English singer-songwriter Elton John, first released on 5 October 1973 as a double LP. The album has sold more than 30 million copies worldwide and is widely regarded as John's magnum opus. Among the 17 tracks, the album contains the hits 'Candle in the Wind', US number-one single 'Bennie and the Jets', 'Goodbye Yellow Brick Road' and 'Saturday Night's Alright for Fighting' plus live favourites 'Funeral for a Friend/Love Lies Bleeding' and 'Harmony'.",
      "price": 242.87,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafd447c1a44758db9366a",
      "artist": "Jimi Hendrix",
      "album": "Electric Ladyland",
      "image": "https://upload.wikimedia.org/wikipedia/en/f/f2/Jimi_Hendrix_-_Electric_Ladyland.jpg",
      "genre": "Rock",
      "tags": "Chico",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/5z090LQztiqh13wYspQvKQ?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Electric Ladyland is the third and final studio album by the Jimi Hendrix Experience and the final studio album released in Hendrix's lifetime before his death in 1970. Released by Reprise Records in North America on October 16, 1968, and by Track Records in the UK nine days later, the double album was the only record from the band produced by Hendrix. By mid-November, it had charted at number one in the US, where it spent two weeks at the top spot. Electric Ladyland was the Experience's most commercially successful release and their only number one album. It peaked at number six in the UK, where it spent 12 weeks on the chart.",
      "price": 210.12,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafd4f7c1a44758db9366b",
      "artist": "Led Zeppelin",
      "album": "Led Zeppelin IV",
      "image": "https://upload.wikimedia.org/wikipedia/en/2/26/Led_Zeppelin_-_Led_Zeppelin_IV.jpg",
      "genre": "Rock",
      "tags": "Chico",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/44Ig8dzqOkvkGDzaUof9lK?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "The untitled fourth studio album by the English rock band Led Zeppelin, commonly known as Led Zeppelin IV, was released on 8 November 1971 by Atlantic Records. It was produced by guitarist Jimmy Page and recorded between December 1970 and February 1971, mostly in the country house Headley Grange. The album is notable for featuring 'Stairway to Heaven', which has been described as the band's signature song.",
      "price": 272.32,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafd587c1a44758db9366c",
      "artist": "Black Sabbath",
      "album": "Paranoid",
      "image": "https://upload.wikimedia.org/wikipedia/en/6/64/Black_Sabbath_-_Paranoid.jpg",
      "genre": "Rock",
      "tags": "Chico",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/132qAo1cDiEJdA3fv4xyNK?utm_source=generator&theme=0' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Paranoid is the second studio album by English heavy metal band Black Sabbath, released in September 1970 through Vertigo Records in England and Warner Bros. Records in the US. The album contains several of the band's signature songs, including 'Iron Man', 'War Pigs' and the title track, which was the band's only Top 20 hit, reaching number 4 in the UK charts.",
      "price": 236.66,
      "access": 0,
      "stock": 99
    },
    {
      "_id": "62cafd6d7c1a44758db9366d",
      "artist": "Black Sabbath",
      "album": "Black Sabbath",
      "image": "https://upload.wikimedia.org/wikipedia/en/thumb/d/da/Black_Sabbath_debut_album.jpg/220px-Black_Sabbath_debut_album.jpg",
      "genre": "Rock",
      "tags": "Chico",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/2T6jeELx5BqH4GMLObBy10?utm_source=generator&theme=0' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Black Sabbath is the debut studio album by English heavy metal band Black Sabbath, released on 13 February 1970 by Vertigo Records in the United Kingdom and Warner Bros. Records in the United States on 1 June 1970. The album is widely regarded as the first heavy metal album. Additionally, the opening track, 'Black Sabbath', has been referred to as the first doom metal song.",
      "price": 266.61,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafd7d7c1a44758db9366e",
      "artist": "Miles Davis",
      "album": "Kind of Blue",
      "image": "https://upload.wikimedia.org/wikipedia/en/thumb/9/9c/MilesDavisKindofBlue.jpg/220px-MilesDavisKindofBlue.jpg",
      "genre": "Jazz",
      "tags": "",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/1weenld61qoidwYuZ1GESA?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Kind of Blue is a studio album by American jazz trumpeter, composer, and bandleader Miles Davis. It was recorded on March 2 and April 22, 1959, at Columbia's 30th Street Studio in New York City, and released on August 17 of that year by Columbia Records. For the recording, Davis led a sextet featuring saxophonists John Coltrane and Julian 'Cannonball' Adderley, pianist Bill Evans, bassist Paul Chambers, and drummer Jimmy Cobb, with new band pianist Wynton Kelly appearing on one track – 'Freddie Freeloader' – in place of Evans.",
      "price": 149.21,
      "access": 0,
      "stock": 99
    },
    {
      "_id": "62cafd897c1a44758db9366f",
      "artist": "John Coltrane",
      "album": "A Love Supreme",
      "image": "https://upload.wikimedia.org/wikipedia/en/thumb/9/9a/John_Coltrane_-_A_Love_Supreme.jpg/220px-John_Coltrane_-_A_Love_Supreme.jpg",
      "genre": "Jazz",
      "tags": "",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/7Eoz7hJvaX1eFkbpQxC5PA?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "A Love Supreme is an album by American jazz saxophonist John Coltrane. He recorded it in one session on December 9, 1964, at Van Gelder Studio in Englewood Cliffs, New Jersey, leading a quartet featuring pianist McCoy Tyner, bassist Jimmy Garrison, and drummer Elvin Jones.",
      "price": 138.16,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafd8e7c1a44758db93670",
      "artist": "Charles Mingus",
      "album": "Mingus Ah Um",
      "image": "https://upload.wikimedia.org/wikipedia/en/thumb/6/65/Mingus_Ah_Um_-_Charles_Mingus.jpg/220px-Mingus_Ah_Um_-_Charles_Mingus.jpg",
      "genre": "Jazz",
      "tags": "",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/4Z8nWz3dGybOP7lhMZpcOo?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Mingus Ah Um is a studio album by American jazz musician Charles Mingus, released in October 1959 by Columbia Records. It was his first album recorded for Columbia. The cover features a painting by S. Neil Fujita. The title is a corruption of an imaginary Latin declension. It is common for Latin students to memorize Latin adjectives by first saying the masculine nominative (usually ending in '-us'), then the feminine nominative ('-a'), and finally the neuter nominative singular ('-um')—implying a transformation of his name, Mingus, Minga, Mingum. The album was inducted into the Grammy Hall of Fame in 2013.",
      "price": 278.76,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafd9e7c1a44758db93671",
      "artist": "Ornette Coleman",
      "album": "The Shape Of Jazz To Come",
      "image": "https://upload.wikimedia.org/wikipedia/en/c/c9/ShapeOfJazzToCome.jpg",
      "genre": "Jazz",
      "tags": "",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/2iPH3iUmpa9ufIpwY76keF?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "The Shape of Jazz to Come is the third album by jazz musician Ornette Coleman. Released on Atlantic Records in 1959, it was his debut on the label and his first album featuring the working quartet including himself, trumpeter Don Cherry, bassist Charlie Haden, and drummer Billy Higgins. The recording session for the album took place on May 22, 1959, at Radio Recorders in Hollywood, California. Although Coleman initially wished for the album to be titled Focus on Sanity after the LP's fourth track, Atlantic producer Nesuhi Ertegun suggested the final title, feeling that it would give consumers 'an idea about the uniqueness of the LP.'",
      "price": 157.76,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafdb57c1a44758db93672",
      "artist": "Sonny Rollins",
      "album": "Saxophone Colossus",
      "image": "https://upload.wikimedia.org/wikipedia/en/thumb/f/ff/Saxophone_Colossus_-_Sonny_Rollins.jpg/220px-Saxophone_Colossus_-_Sonny_Rollins.jpg",
      "genre": "Jazz",
      "tags": "",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/0yodD8uAkAT5UmrlF2xy97?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Saxophone Colossus is the sixth studio album by American jazz saxophonist Sonny Rollins. Perhaps Rollins's best-known album, it is often considered his breakthrough record. It was recorded monophonically on June 22, 1956, with producer Bob Weinstock and engineer Rudy Van Gelder at the latter's studio in Hackensack, New Jersey. Rollins led a quartet on the album that included pianist Tommy Flanagan, bassist Doug Watkins, and drummer Max Roach. Saxophone Colossus was released by Prestige Records to critical success and helped establish Rollins as a prominent jazz artist.",
      "price": 330.56,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafdc57c1a44758db93673",
      "artist": "The Dave Brubeck Quartet",
      "album": "Time Out",
      "image": "https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/Time_out_album_cover.jpg/220px-Time_out_album_cover.jpg",
      "genre": "Jazz",
      "tags": "",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/0yodD8uAkAT5UmrlF2xy97?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Time Out is a studio album by the American jazz group the Dave Brubeck Quartet, released in 1959 on Columbia Records. Recorded at Columbia's 30th Street Studio in New York City, it is based upon the use of time signatures that were unusual for jazz such as 9/8 6/4 and 5/4. The album is a subtle blend of cool and West Coast jazz.",
      "price": 291.71,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafdd47c1a44758db93674",
      "artist": "Art Blakey & The Jazz Messengers",
      "album": "Moanin'",
      "image": "https://upload.wikimedia.org/wikipedia/en/thumb/c/cb/Moanin%27_%28Art_Blakey%29.jpg/220px-Moanin%27_%28Art_Blakey%29.jpg",
      "genre": "Jazz",
      "tags": "",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/5PzlTnVafjgt5RtjTdIKoC?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Moanin' (originally titled Art Blakey and the Jazz Messengers) is a jazz album by Art Blakey and the Jazz Messengers recorded in 1958 for the Blue Note label and released in 1959.",
      "price": 199.92,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafdde7c1a44758db93675",
      "artist": "Billie Holiday",
      "album": "Lady In Satin",
      "image": "https://upload.wikimedia.org/wikipedia/en/5/52/Ladyinsatin2.jpg",
      "genre": "Jazz",
      "tags": "",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/4LrLP7DM1KBj8r2Sc098JA?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Lady in Satin is an album by the jazz singer Billie Holiday released in 1958 on Columbia Records, catalogue CL 1157 in mono and CS 8048 in stereo. It is the penultimate album completed by the singer and last released in her lifetime (her final album, Last Recording, being recorded in March 1959 and released just after her death). The original album was produced by Irving Townsend and engineered by Fred Plaut.",
      "price": 169.63,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafdea7c1a44758db93676",
      "artist": "Stan Getz & João Gilberto",
      "album": "Getz/Gilberto",
      "image": "https://upload.wikimedia.org/wikipedia/en/thumb/9/96/Getz-gilberto.jpg/220px-Getz-gilberto.jpg",
      "genre": "Bossa Nova",
      "tags": "Chico",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/playlist/4D6VHkzFpE1Hu006RABcdI?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Getz/Gilberto is an album by American saxophonist Stan Getz and Brazilian guitarist João Gilberto, featuring pianist and composer Antônio Carlos Jobim (Tom Jobim), who also composed many of the tracks. It was released in March 1964 by Verve Records. The album features the vocals of Astrud Gilberto on two tracks, 'Garota de Ipanema' ('The Girl from Ipanema') and 'Corcovado'. The artwork was done by artist Olga Albizu. Getz/Gilberto is a jazz and bossa nova album and includes tracks such as 'Desafinado', 'Corcovado', and 'Garota de Ipanema'. The last received a Grammy Award for Record of the Year and started Astrud Gilberto's career. 'Doralice' and 'Para Machucar Meu Coração' strengthened Gilberto's and Jobim's respect for the tradition of pre-bossa nova samba.",
      "price": 236.52,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafdfb7c1a44758db93677",
      "artist": "Nara Leão",
      "album": "Dez Anos Depois",
      "image": "https://upload.wikimedia.org/wikipedia/en/thumb/2/22/Nara_Le%C3%A3o_10.jpg/220px-Nara_Le%C3%A3o_10.jpg",
      "genre": "Bossa Nova",
      "tags": "",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/14vNVSBK4R5XpKUEUOTjvd?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Dez anos depois is a 1971 double album of bossa nova standards by Brazilian singer Nara Leão.<br/>The first LP is entirely acoustic. The arrangements and accompaniment, made by Brazilian guitarist Tuca, with occasional piano lines, were recorded in France; Nara was living in Paris at the time. The second LP was recorded in Rio; Nara's guitar and vocal were tracked separately from the accompaniment and orchestration, which were done at a studio with arrangers Roberto Menescal, Luiz Eça, and Rogério Duprat.",
      "price": 436.52,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafe057c1a44758db93678",
      "artist": "Elis Regina & Antônio Carlos Jobim",
      "album": "Elis & Tom",
      "image": "https://upload.wikimedia.org/wikipedia/en/thumb/6/64/Elistom.jpg/220px-Elistom.jpg",
      "genre": "Bossa Nova",
      "tags": "",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/3SE9n6EaVOJ81KA1KPLUWS?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Elis & Tom is a bossa nova album, released in 1974, recorded by Brazilian singer Elis Regina and singer-songwriter Antônio Carlos Jobim.<br/>Recorded over a 16-day period at MGM Studios in Los Angeles, California, the album was an old wish of Regina, who always wanted to record a full album of Jobim's songs with him. This finally came true in 1974, when Elis was celebrating her 10th anniversary as an artist of Philips Records. The label approved the project as a gift for her.",
      "price": 266.45,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafe0e7c1a44758db93679",
      "artist": "Antônio Carlos Jobim",
      "album": "Wave",
      "image": "https://upload.wikimedia.org/wikipedia/en/thumb/a/ad/Wavejobim.jpg/220px-Wavejobim.jpg",
      "genre": "Bossa Nova",
      "tags": "",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/5SSyex1jdJe9h3lbqESv1T?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Wave is the fifth studio album by Brazilian jazz musician Antônio Carlos Jobim, released in 1967 on A&M Records. Recorded in the US with mostly American musicians, it peaked at number 114 on the Billboard 200 chart, as well as number 5 on the Jazz Albums chart.<br/>Wave includes an ensemble of elite jazz musicians, including trombonists Urbie Green and Jimmy Cleveland, flautist Jerome Richardson, and bassist Ron Carter. Prolific jazz album cover photographer Pete Turner created the psychedelic solarized cover picture of a giraffe.",
      "price": 206.12,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafe1a7c1a44758db9367a",
      "artist": "Caetano Veloso",
      "album": "Caetano Veloso",
      "image": "https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Caetano_Veloso_1968.jpg/220px-Caetano_Veloso_1968.jpg",
      "genre": "Bossa Nova",
      "tags": "",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/3idXLXoZDLQyxAHF97yguf?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Caetano Veloso is the debut solo album by the artist of the same name, released in Brazil in 1968. He had released Domingo the year before in collaboration with Gal Costa. It was one of the first Tropicália efforts, and features arrangements by Júlio Medaglia, Damiano Cozzella, and Sandino Hohagen, as well as an eclectic assortment of influences, demonstrating the 'antropofagia' (artistic cannibalism) of the Tropicália movement. Sounds from psychedelia, rock, pop, Indian music, bossa nova, Bahian music and other genres appear on the album. It includes the hit songs 'Alegria, Alegria', 'Tropicália', and 'Soy loco por ti, América'.",
      "price": 297.12,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafe2f7c1a44758db9367b",
      "artist": "Lamp",
      "album": "For Lovers - 恋人へ",
      "image": "https://m.media-amazon.com/images/I/81B3CPLhlvL._SS500_.jpg",
      "genre": "Bossa Nova",
      "tags": "",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/0gwS2D9sukMLXNvleEnYr2?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Despite selling less than their first album, For Lovers, released on 11 February 2004, became a fan favorite over the years.",
      "price": 237.12,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafe3f7c1a44758db9367c",
      "artist": "Jorge Ben",
      "album": "Samba Esquema Novo",
      "image": "https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/Jorgeben_samba_esquema_novo.jpg/220px-Jorgeben_samba_esquema_novo.jpg",
      "genre": "Bossa Nova",
      "tags": "Chico",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/3xWp6y0HGsHZlXljNs7VRy?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Samba Esquema Novo is the 1963 debut album by Brazilian singer-songwriter and guitarist Jorge Ben. It includes the original recording of the international hit 'Mas, que Nada!'.",
      "price": 146.31,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafe507c1a44758db9367d",
      "artist": "Gal Costa & Caetano Veloso",
      "album": "Domingo",
      "image": "https://upload.wikimedia.org/wikipedia/en/thumb/3/32/Gal_Costa...jpg/220px-Gal_Costa...jpg",
      "genre": "Bossa Nova",
      "tags": "",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/4d8IqRNN8UX3vxtS6jnBA8?utm_source=generator' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "Domingo is the debut studio album by Gal Costa and Caetano Veloso. It was released on Philips Records in 1967",
      "price": 176.31,
      "access": 0,
      "stock": 100
    },
    {
      "_id": "62cafe6d7c1a44758db9367e",
      "artist": "Iron Maiden",
      "album": "The Number of the Beast",
      "image": "https://upload.wikimedia.org/wikipedia/en/3/32/IronMaiden_NumberOfBeast.jpg",
      "genre": "Rock",
      "tags": "Chico",
      "embed": "<iframe style='border-radius:12px' src='https://open.spotify.com/embed/album/5S3gls8Kjn8KVmqlIDEBbO?utm_source=generator&theme=0' width='100%' height='238' frameBorder='0' allowfullscreen='' allow='autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture'></iframe>",
      "description": "The Number of the Beast is the third studio album by English heavy metal band Iron Maiden. It was released on 22 March 1982 in the United Kingdom by EMI Records and in the United States by Harvest and Capitol Records. The album was their first to feature vocalist Bruce Dickinson and their last with drummer Clive Burr.",
      "price": 236.66,
      "access": 0,
      "stock": 94
    }
  ]